name: Publish to Comfy registry
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - "pyproject.toml"

permissions:
  issues: write

jobs:
  publish-node:
    name: Publish Custom Node to registry
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'HavocsCall' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Extract Version From Tag
        id: get_version
        uses: battila7/get-version-action@v2
      
      - name: Modify pyproject.toml
        id: sub_manifest_link_version
        uses: cschleiden/replace-tokens@v1
        with:
          files: 'pyproject.toml'
        env:
          VERSION: ${{steps.get_version.outputs.version-without-v}}
          REPO: https://github.com/${{github.repository}}

      - name: Publish Custom Node
        uses: Comfy-Org/publish-node-action@v1
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}